<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:14:54.
 */
class mobileResourceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var mobileResource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new mobileResource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers mobileResource::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setIphone
     * @todo   Implement testSetIphone().
     */
    public function testSetIphone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setIpad
     * @todo   Implement testSetIpad().
     */
    public function testSetIpad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setAndrod
     * @todo   Implement testSetAndrod().
     */
    public function testSetAndrod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setBlackberry
     * @todo   Implement testSetBlackberry().
     */
    public function testSetBlackberry() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setPalm
     * @todo   Implement testSetPalm().
     */
    public function testSetPalm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::setWindows
     * @todo   Implement testSetWindows().
     */
    public function testSetWindows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::mobile_device_detect
     * @todo   Implement testMobile_device_detect().
     */
    public function testMobile_device_detect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers mobileResource::IsMobile
     * @todo   Implement testIsMobile().
     */
    public function testIsMobile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
